# FindSDL2_image.cmake

find_package(SDL2 REQUIRED)
find_package(PkgConfig REQUIRED)
pkg_check_modules(SDL2IMAGE REQUIRED SDL2_image)

set(SDL2_IMAGE_INCLUDE_DIRS ${SDL2IMAGE_INCLUDE_DIRS})
set(SDL2_IMAGE_LIBRARIES ${SDL2IMAGE_LIBRARIES})
set(SDL2_IMAGE_FOUND TRUE)