name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Linux Build Steps
    - name: Install Dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-ttf-dev

    - name: Configure CMake (Linux)
      if: runner.os == 'Linux'
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build (Linux)
      if: runner.os == 'Linux'
      run: cmake --build build --config Release

    - name: Prepare Release Directory (Linux)
      if: runner.os == 'Linux'
      run: |
        mkdir -p release
        cp build/campo_de_batalha release/
        cp -r resources release/

    - name: Upload Release Artifact (Linux)
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v3
      with:
        name: CampoDeBatalha-Linux
        path: release/

    # Windows Build Steps (Placeholder)
    - name: Install Dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        echo "Installing dependencies on Windows..."
        # TODO: Add Windows dependency installation commands here

    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      run: |
        echo "Configuring CMake on Windows..."
        # TODO: Add CMake configuration commands for Windows

    - name: Build (Windows)
      if: runner.os == 'Windows'
      run: |
        echo "Building on Windows..."
        # TODO: Add build commands for Windows

    - name: Prepare Release Directory (Windows)
      if: runner.os == 'Windows'
      run: |
        echo "Preparing release directory on Windows..."
        # TODO: Add commands to prepare the release directory on Windows

    - name: Upload Release Artifact (Windows)
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v3
      with:
        name: CampoDeBatalha-Windows
        path: release/
